language: node_js
node_js:
- '6'
- '5'
- '4'
- '0.12'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: npm
  email: m@xen.ru
  api_key:
    secure: XXX
  on:
    tags: true
    repo: xen/tgmde
    branch: production
